"""EpistemicFrettingService — Epistemic Fretting Detection.

Detects epistemic fretting — small oscillating movements between ideas
in contact causing surface damage and debris generation.
"""

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

logger = structlog.get_logger(__name__)

EPISTEMIC_FRETTING_SYSTEM = """You are an epistemic fretting specialist. Given an idea oscillation pattern, assess whether small movements cause surface damage:

Key concepts:
- Epistemic fretting: small oscillations causing surface damage
- Amplitude: size of the oscillating movement
- Frequency: how often the oscillation occurs
- Oxide layer: protective surface removed by fretting
- Debris: particles generated by the oscillation
- Crack initiation: fretting starting fatigue cracks
- Fretting fatigue: combined fretting and cyclic stress

When epistemic fretting IS present:
- Small oscillating movements between ideas causing damage
- Size of the back-and-forth movement
- Frequency of the repetitive oscillation
- Protective surface layers being removed
- Particles generated by the oscillation
- Damage initiating deeper cracks
- Combined oscillation and stress causing failure

When stable contact is present:
- Ideas in stable contact without oscillation
- No back-and-forth movement
- No repetitive oscillation
- Protective surfaces intact
- No particle generation
- No crack initiation from contact
- No combined damage mechanisms

Output JSON with: fretting_present (bool), severity (none/mild/moderate/severe), amplitude (what oscillation size), frequency (how often), oxide_removal (what protection lost), crack_initiation (what deeper damage), recommendation (stable_contact/mild_fretting/significant_fretting/major_oscillation_damage/eliminate_relative_motion)."""

EPISTEMIC_FRETTING_PROMPT = """Detect epistemic fretting:

Amplitude: {amplitude}
Frequency: {frequency}
Oxide removal: {oxide_removal}
Crack initiation: {crack_initiation}
Domain: {domain}
Context: {context}

Are small oscillating movements between ideas in contact causing surface damage and debris generation? Return ONLY valid JSON."""


class EpistemicFrettingService:
    """Detects epistemic fretting — small oscillations causing damage."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def detect(
        self,
        amplitude: str,
        *,
        frequency: str = "",
        oxide_removal: str = "",
        crack_initiation: str = "",
        domain: str = "",
        context: str = "",
    ) -> dict:
        """Detect epistemic fretting."""
        from app.clients.llm_client import LLMClient
        from app.services.llm_utils import parse_llm_json

        llm = LLMClient()
        raw = await llm.complete(
            prompt=EPISTEMIC_FRETTING_PROMPT.format(
                amplitude=amplitude,
                frequency=frequency or "Not specified",
                oxide_removal=oxide_removal or "Not specified",
                crack_initiation=crack_initiation or "Not specified",
                domain=domain or "general",
                context=context or "No additional context",
            ),
            system=EPISTEMIC_FRETTING_SYSTEM,
            max_tokens=4096,
            temperature=0.3,
        )
        data = parse_llm_json(raw)

        return {
            "amplitude": amplitude[:200],
            "fretting_present": data.get("fretting_present", False),
            "severity": data.get("severity", ""),
            "frequency": data.get("frequency", ""),
            "oxide_removal": data.get("oxide_removal", ""),
            "crack_initiation": data.get("crack_initiation", ""),
            "recommendation": data.get("recommendation", ""),
        }
