"""EpistemicHarmonicService — Epistemic Harmonic Detection.

Detects epistemic harmonics — false patterns created by the
interaction of ideas at related frequencies, phantom signals.
"""

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

logger = structlog.get_logger(__name__)

EPISTEMIC_HARMONIC_SYSTEM = """You are an epistemic harmonic specialist. Given a pattern detection scenario, assess whether apparent patterns are harmonics rather than real signals:

Key concepts:
- Epistemic harmonic: phantom pattern created by interaction of ideas
- False pattern: pattern that exists only as artifact of combination
- Overtone: secondary pattern generated by primary ideas interacting
- Interference pattern: pattern from overlapping idea waves
- Phantom signal: signal that doesn't exist in reality
- Frequency artifact: artifact of the frequency of observation
- Aliasing: false pattern from insufficient sampling

When epistemic harmonics ARE present:
- Apparent patterns that are artifacts of idea interaction
- False patterns existing only as combination artifacts
- Secondary patterns generated by primary ideas interacting
- Patterns from overlapping idea waves
- Signals that don't exist in underlying reality
- Artifacts of observation frequency
- False patterns from insufficient sampling

When genuine patterns are present:
- Patterns existing in underlying reality
- Patterns not artifacts of combination
- Primary patterns directly observed
- No interference creating false patterns
- Signals corresponding to real phenomena
- Patterns independent of observation frequency
- Patterns robust to different sampling rates

Output JSON with: harmonic_present (bool), severity (none/mild/moderate/severe), pattern (what phantom pattern appears), sources (what ideas interact to create it), mechanism (how harmonic is generated), reality_check (why pattern is not real), recommendation (genuine_pattern/mild_harmonic/significant_phantom_pattern/major_false_signal/verify_pattern_independence)."""

EPISTEMIC_HARMONIC_PROMPT = """Detect epistemic harmonics:

Pattern: {pattern}
Sources: {sources}
Mechanism: {mechanism}
Reality check: {reality_check}
Domain: {domain}
Context: {context}

Are apparent patterns actually harmonics — artifacts of idea interaction rather than real signals? Return ONLY valid JSON."""


class EpistemicHarmonicService:
    """Detects epistemic harmonics — phantom patterns from idea interaction."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def detect(
        self,
        pattern: str,
        *,
        sources: str = "",
        mechanism: str = "",
        reality_check: str = "",
        domain: str = "",
        context: str = "",
    ) -> dict:
        """Detect epistemic harmonics."""
        from app.clients.llm_client import LLMClient
        from app.services.llm_utils import parse_llm_json

        llm = LLMClient()
        raw = await llm.complete(
            prompt=EPISTEMIC_HARMONIC_PROMPT.format(
                pattern=pattern,
                sources=sources or "Not specified",
                mechanism=mechanism or "Not specified",
                reality_check=reality_check or "Not specified",
                domain=domain or "general",
                context=context or "No additional context",
            ),
            system=EPISTEMIC_HARMONIC_SYSTEM,
            max_tokens=4096,
            temperature=0.3,
        )
        data = parse_llm_json(raw)

        return {
            "pattern": pattern[:200],
            "harmonic_present": data.get("harmonic_present", False),
            "severity": data.get("severity", ""),
            "sources": data.get("sources", ""),
            "mechanism": data.get("mechanism", ""),
            "reality_check": data.get("reality_check", ""),
            "recommendation": data.get("recommendation", ""),
        }
