"""GenerationEffectService — Generation Effect Detection.

Detects generation effect — information is better remembered
when it is generated by the learner rather than simply read.
Slamecka & Graf (1978). Self-generated answers stick better
than provided answers. But this can lead to overconfidence
in self-generated (possibly wrong) conclusions and
undervaluing externally provided (possibly correct) information.
"""

import structlog
from sqlalchemy.ext.asyncio import AsyncSession

logger = structlog.get_logger(__name__)

GENERATION_EFFECT_SYSTEM = """You are a generation effect specialist. Given a learning or knowledge situation, assess whether the generation effect is creating bias — either beneficial memory enhancement or problematic overconfidence in self-generated conclusions:

Key concepts (Slamecka & Graf, 1978):
- Generation effect: self-generated info remembered better
- Active learning advantage: generating > reading for retention
- Overconfidence in generated: self-made conclusions feel more certain
- Not-invented-here interaction: dismissing external info
- Effort-accuracy confusion: effort of generation ≠ accuracy
- Fluency misattribution: ease of generation → perceived truth
- Self-generated validity: "I figured it out myself, so it must be right"

When generation effect IS causing problems:
- Overconfidence in self-derived conclusions vs expert knowledge
- Dismissing provided information in favor of own reasoning
- "I worked it out myself" used as evidence of correctness
- Preferring own analysis over established findings
- Difficulty updating self-generated beliefs with new evidence
- "I thought about it carefully" substituting for verification
- Reinventing the wheel rather than learning from others

When the generation effect IS beneficial:
- Self-generation is being used as a learning strategy
- The person verifies self-generated conclusions
- Active engagement improves understanding without overconfidence
- The person distinguishes memory strength from accuracy
- Self-generation is combined with external validation

Output JSON with: generation_effect_present (bool), severity (none/mild/moderate/severe), situation (what knowledge situation is occurring), self_generated (what was self-generated), external_info (what external information is available), overconfidence (is there overconfidence in self-generated conclusions?), dismissal (is external information being dismissed?), verification (has the self-generated conclusion been verified?), recommendation (effect_beneficial/mild_overconfidence/significant_dismissal/major_generation_bias/verify_self_generated_conclusions)."""

GENERATION_EFFECT_PROMPT = """Detect generation effect bias:

Situation: {situation}
Self-generated: {generated}
External info: {external}
Confidence: {confidence}
Domain: {domain}
Context: {context}

Is the generation effect causing overconfidence in self-derived conclusions? Return ONLY valid JSON."""


class GenerationEffectService:
    """Detects generation effect bias — overconfidence in self-generated conclusions."""

    def __init__(self, db: AsyncSession):
        self.db = db

    async def detect(
        self,
        situation: str,
        *,
        generated: str = "",
        external: str = "",
        confidence: str = "",
        domain: str = "",
        context: str = "",
    ) -> dict:
        """Detect generation effect."""
        from app.clients.llm_client import LLMClient
        from app.services.llm_utils import parse_llm_json

        llm = LLMClient()
        raw = await llm.complete(
            prompt=GENERATION_EFFECT_PROMPT.format(
                situation=situation,
                generated=generated or "Not specified",
                external=external or "Not specified",
                confidence=confidence or "Not specified",
                domain=domain or "general",
                context=context or "No additional context",
            ),
            system=GENERATION_EFFECT_SYSTEM,
            max_tokens=4096,
            temperature=0.3,
        )
        data = parse_llm_json(raw)

        return {
            "situation": situation[:200],
            "generation_effect_present": data.get("generation_effect_present", False),
            "severity": data.get("severity", ""),
            "self_generated": data.get("self_generated", ""),
            "external_info": data.get("external_info", ""),
            "overconfidence": data.get("overconfidence", ""),
            "dismissal": data.get("dismissal", ""),
            "verification": data.get("verification", ""),
            "recommendation": data.get("recommendation", ""),
        }
