"""add_deep_analysis_to_papers

Revision ID: 08b6f9cddb0a
Revises: b1c2d3e4f5a6
Create Date: 2026-04-01 10:35:19.393971

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "08b6f9cddb0a"
down_revision: Union[str, None] = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("rule_type", sa.String(length=30), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alert_rules_deleted_at"), "alert_rules", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_alert_rules_user_id"), "alert_rules", ["user_id"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_table(
        "collections",
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default="00000000-0000-0000-0000-000000000001",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("is_smart", sa.Boolean(), nullable=False),
        sa.Column(
            "smart_filter", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("paper_count", sa.Integer(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collections_user_id"), "collections", ["user_id"], unique=False
    )
    op.create_table(
        "digests",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("paper_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("paper_count", sa.Integer(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_digests_deleted_at"), "digests", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_digests_user_id"), "digests", ["user_id"], unique=False)
    op.create_table(
        "institutions",
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("ror_id", sa.String(length=30), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=5), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column(
            "raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_institutions_deleted_at"), "institutions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_institutions_openalex_id"),
        "institutions",
        ["openalex_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_institutions_ror_id"), "institutions", ["ror_id"], unique=False
    )
    op.create_table(
        "rss_feeds",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("publisher", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("etag", sa.String(length=200), nullable=True),
        sa.Column("last_modified", sa.String(length=100), nullable=True),
        sa.Column("poll_error_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("total_items_discovered", sa.Integer(), nullable=False),
        sa.Column("last_item_count", sa.Integer(), nullable=False),
        sa.Column("pdf_capability", sa.String(length=20), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_rss_feeds_deleted_at"), "rss_feeds", ["deleted_at"], unique=False
    )
    op.create_table(
        "tags",
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default="00000000-0000-0000-0000-000000000001",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_user_tag_name"),
    )
    op.create_index(op.f("ix_tags_deleted_at"), "tags", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "representative_docs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("paper_count", sa.Integer(), nullable=False),
        sa.Column("trend_direction", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topics_deleted_at"), "topics", ["deleted_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("personal", "member", "reviewer", "admin", name="userrole"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "venues",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=True),
        sa.Column("issn", sa.String(length=20), nullable=True),
        sa.Column("eissn", sa.String(length=20), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("sjr_quartile", sa.String(length=5), nullable=True),
        sa.Column("ccf_rank", sa.String(length=5), nullable=True),
        sa.Column("impact_factor", sa.Float(), nullable=True),
        sa.Column("h_index", sa.Integer(), nullable=True),
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_venues_deleted_at"), "venues", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_venues_issn"), "venues", ["issn"], unique=False)
    op.create_index(
        op.f("ix_venues_openalex_id"), "venues", ["openalex_id"], unique=True
    )
    op.create_table(
        "webhooks",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secret", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhooks_deleted_at"), "webhooks", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_webhooks_user_id"), "webhooks", ["user_id"], unique=False)
    op.create_table(
        "authors",
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("orcid", sa.String(length=30), nullable=True),
        sa.Column("semantic_scholar_id", sa.String(length=50), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("h_index", sa.Integer(), nullable=True),
        sa.Column("paper_count", sa.Integer(), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("institution_id", sa.UUID(), nullable=True),
        sa.Column(
            "raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authors_deleted_at"), "authors", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_authors_openalex_id"), "authors", ["openalex_id"], unique=True
    )
    op.create_index(op.f("ix_authors_orcid"), "authors", ["orcid"], unique=False)
    op.create_index(
        op.f("ix_authors_semantic_scholar_id"),
        "authors",
        ["semantic_scholar_id"],
        unique=False,
    )
    op.create_table(
        "papers",
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("arxiv_id", sa.String(length=50), nullable=True),
        sa.Column("pmid", sa.String(length=20), nullable=True),
        sa.Column("openalex_id", sa.String(length=50), nullable=True),
        sa.Column("semantic_scholar_id", sa.String(length=50), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("paper_type", sa.String(length=50), nullable=True),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("venue_id", sa.UUID(), nullable=True),
        sa.Column("volume", sa.String(length=50), nullable=True),
        sa.Column("issue", sa.String(length=50), nullable=True),
        sa.Column("pages", sa.String(length=50), nullable=True),
        sa.Column("oa_status", sa.String(length=20), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("influential_citation_count", sa.Integer(), nullable=True),
        sa.Column(
            "citation_count_updated_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("pdf_path", sa.Text(), nullable=True),
        sa.Column(
            "remote_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("has_full_text", sa.Boolean(), nullable=False),
        sa.Column("full_text_markdown", sa.Text(), nullable=True),
        sa.Column(
            "markdown_provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("grobid_tei", sa.Text(), nullable=True),
        sa.Column("ingestion_status", sa.String(length=20), nullable=False),
        sa.Column("parser_version", sa.String(length=20), nullable=True),
        sa.Column("ingestion_error", sa.Text(), nullable=True),
        sa.Column("reading_status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "summary_provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("highlights", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "highlights_provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "contributions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "contributions_provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "limitations_provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column(
            "local_annotations", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "parsed_sections", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "parsed_figures", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "deep_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("deep_analysis_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_papers_arxiv_id"), "papers", ["arxiv_id"], unique=False)
    op.create_index(
        op.f("ix_papers_deleted_at"), "papers", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_papers_doi"), "papers", ["doi"], unique=True)
    op.create_index(
        op.f("ix_papers_openalex_id"), "papers", ["openalex_id"], unique=False
    )
    op.create_index(op.f("ix_papers_pmid"), "papers", ["pmid"], unique=False)
    op.create_index(
        op.f("ix_papers_published_at"), "papers", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_papers_semantic_scholar_id"),
        "papers",
        ["semantic_scholar_id"],
        unique=False,
    )
    op.create_table(
        "saved_searches",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default="00000000-0000-0000-0000-000000000001",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_searches_collection_id"),
        "saved_searches",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_searches_deleted_at"),
        "saved_searches",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_searches_user_id"), "saved_searches", ["user_id"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=True),
        sa.Column("alert_type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["alert_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_deleted_at"), "alerts", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.create_table(
        "annotations",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("annotation_type", sa.String(length=20), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("position", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotations_deleted_at"), "annotations", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_paper_id"), "annotations", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_annotations_user_id"), "annotations", ["user_id"], unique=False
    )
    op.create_table(
        "claims",
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=30), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("hedging_level", sa.String(length=20), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("section_ref", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_claims_deleted_at"), "claims", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_claims_paper_id"), "claims", ["paper_id"], unique=False)
    op.create_table(
        "collection_papers",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_collection_papers_collection_id"),
        "collection_papers",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_papers_paper_id"),
        "collection_papers",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "glossary_terms",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("term", sa.String(length=200), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("domain", sa.String(length=100), nullable=True),
        sa.Column("source_paper_id", sa.UUID(), nullable=True),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=False),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_glossary_terms_deleted_at"),
        "glossary_terms",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_glossary_terms_user_id"), "glossary_terms", ["user_id"], unique=False
    )
    op.create_table(
        "knowledge_cards",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("card_type", sa.String(length=20), nullable=False),
        sa.Column("difficulty", sa.String(length=10), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("repetition", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_cards_deleted_at"),
        "knowledge_cards",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_cards_user_id"), "knowledge_cards", ["user_id"], unique=False
    )
    op.create_table(
        "metadata_provenance",
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metadata_provenance_paper_id"),
        "metadata_provenance",
        ["paper_id"],
        unique=False,
    )
    op.create_table(
        "paper_authors",
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_corresponding", sa.Boolean(), nullable=False),
        sa.Column("raw_affiliation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("paper_id", "author_id"),
    )
    op.create_table(
        "paper_references",
        sa.Column("citing_paper_id", sa.UUID(), nullable=False),
        sa.Column("cited_paper_id", sa.UUID(), nullable=True),
        sa.Column("raw_title", sa.Text(), nullable=True),
        sa.Column("raw_authors", sa.Text(), nullable=True),
        sa.Column("raw_year", sa.String(length=10), nullable=True),
        sa.Column("raw_doi", sa.String(length=255), nullable=True),
        sa.Column("raw_string", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cited_paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["citing_paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_references_cited_paper_id"),
        "paper_references",
        ["cited_paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_paper_references_citing_paper_id"),
        "paper_references",
        ["citing_paper_id"],
        unique=False,
    )
    op.create_table(
        "paper_tags",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.Column(
            "tagged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_tags_paper_id"), "paper_tags", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_tags_tag_id"), "paper_tags", ["tag_id"], unique=False
    )
    op.create_table(
        "paper_topics",
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_topics_paper_id"), "paper_topics", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_topics_topic_id"), "paper_topics", ["topic_id"], unique=False
    )
    op.create_table(
        "paper_versions",
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("arxiv_version", sa.String(length=10), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("pdf_path", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_paper_versions_deleted_at"),
        "paper_versions",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "ragflow_document_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("ragflow_dataset_id", sa.String(length=255), nullable=False),
        sa.Column("ragflow_document_id", sa.String(length=255), nullable=True),
        sa.Column("sync_hash", sa.String(length=64), nullable=True),
        sa.Column("parse_status", sa.String(length=20), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("collection_id"),
        sa.UniqueConstraint("paper_id"),
    )
    op.create_table(
        "reading_logs",
        sa.Column("user_id", sa.String(length=50), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_logs_deleted_at"), "reading_logs", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_reading_logs_paper_id"), "reading_logs", ["paper_id"], unique=False
    )
    op.create_index(
        op.f("ix_reading_logs_user_id"), "reading_logs", ["user_id"], unique=False
    )
    op.create_table(
        "reading_path_cache",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("from_paper_id", sa.UUID(), nullable=False),
        sa.Column("to_paper_id", sa.UUID(), nullable=False),
        sa.Column(
            "path_paper_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reading_path_cache_from_paper_id"),
        "reading_path_cache",
        ["from_paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reading_path_cache_to_paper_id"),
        "reading_path_cache",
        ["to_paper_id"],
        unique=False,
    )
    op.create_table(
        "reproduction_attempts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("code_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reproduction_attempts_paper_id"),
        "reproduction_attempts",
        ["paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reproduction_attempts_user_id"),
        "reproduction_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_corrections",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=False),
        sa.Column(
            "original_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "corrected_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_corrections_paper_id"),
        "user_corrections",
        ["paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_corrections_user_id"),
        "user_corrections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_reading_status",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default="00000000-0000-0000-0000-000000000001",
            nullable=False,
        ),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "paper_id", name="uq_user_paper_reading"),
    )
    op.create_index(
        op.f("ix_user_reading_status_paper_id"),
        "user_reading_status",
        ["paper_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_reading_status_user_id"),
        "user_reading_status",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "evidence_links",
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("paper_id", sa.UUID(), nullable=False),
        sa.Column("evidence_type", sa.String(length=20), nullable=False),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("strength", sa.String(length=20), nullable=True),
        sa.Column("is_sufficient", sa.Boolean(), nullable=True),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["claim_id"],
            ["claims.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_links_claim_id"), "evidence_links", ["claim_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_links_deleted_at"),
        "evidence_links",
        ["deleted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_links_deleted_at"), table_name="evidence_links")
    op.drop_index(op.f("ix_evidence_links_claim_id"), table_name="evidence_links")
    op.drop_table("evidence_links")
    op.drop_index(
        op.f("ix_user_reading_status_user_id"), table_name="user_reading_status"
    )
    op.drop_index(
        op.f("ix_user_reading_status_paper_id"), table_name="user_reading_status"
    )
    op.drop_table("user_reading_status")
    op.drop_index(op.f("ix_user_corrections_user_id"), table_name="user_corrections")
    op.drop_index(op.f("ix_user_corrections_paper_id"), table_name="user_corrections")
    op.drop_table("user_corrections")
    op.drop_index(
        op.f("ix_reproduction_attempts_user_id"), table_name="reproduction_attempts"
    )
    op.drop_index(
        op.f("ix_reproduction_attempts_paper_id"), table_name="reproduction_attempts"
    )
    op.drop_table("reproduction_attempts")
    op.drop_index(
        op.f("ix_reading_path_cache_to_paper_id"), table_name="reading_path_cache"
    )
    op.drop_index(
        op.f("ix_reading_path_cache_from_paper_id"), table_name="reading_path_cache"
    )
    op.drop_table("reading_path_cache")
    op.drop_index(op.f("ix_reading_logs_user_id"), table_name="reading_logs")
    op.drop_index(op.f("ix_reading_logs_paper_id"), table_name="reading_logs")
    op.drop_index(op.f("ix_reading_logs_deleted_at"), table_name="reading_logs")
    op.drop_table("reading_logs")
    op.drop_table("ragflow_document_mappings")
    op.drop_index(op.f("ix_paper_versions_deleted_at"), table_name="paper_versions")
    op.drop_table("paper_versions")
    op.drop_index(op.f("ix_paper_topics_topic_id"), table_name="paper_topics")
    op.drop_index(op.f("ix_paper_topics_paper_id"), table_name="paper_topics")
    op.drop_table("paper_topics")
    op.drop_index(op.f("ix_paper_tags_tag_id"), table_name="paper_tags")
    op.drop_index(op.f("ix_paper_tags_paper_id"), table_name="paper_tags")
    op.drop_table("paper_tags")
    op.drop_index(
        op.f("ix_paper_references_citing_paper_id"), table_name="paper_references"
    )
    op.drop_index(
        op.f("ix_paper_references_cited_paper_id"), table_name="paper_references"
    )
    op.drop_table("paper_references")
    op.drop_table("paper_authors")
    op.drop_index(
        op.f("ix_metadata_provenance_paper_id"), table_name="metadata_provenance"
    )
    op.drop_table("metadata_provenance")
    op.drop_index(op.f("ix_knowledge_cards_user_id"), table_name="knowledge_cards")
    op.drop_index(op.f("ix_knowledge_cards_deleted_at"), table_name="knowledge_cards")
    op.drop_table("knowledge_cards")
    op.drop_index(op.f("ix_glossary_terms_user_id"), table_name="glossary_terms")
    op.drop_index(op.f("ix_glossary_terms_deleted_at"), table_name="glossary_terms")
    op.drop_table("glossary_terms")
    op.drop_index(op.f("ix_collection_papers_paper_id"), table_name="collection_papers")
    op.drop_index(
        op.f("ix_collection_papers_collection_id"), table_name="collection_papers"
    )
    op.drop_table("collection_papers")
    op.drop_index(op.f("ix_claims_paper_id"), table_name="claims")
    op.drop_index(op.f("ix_claims_deleted_at"), table_name="claims")
    op.drop_table("claims")
    op.drop_index(op.f("ix_annotations_user_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_paper_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_deleted_at"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_deleted_at"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_saved_searches_user_id"), table_name="saved_searches")
    op.drop_index(op.f("ix_saved_searches_deleted_at"), table_name="saved_searches")
    op.drop_index(op.f("ix_saved_searches_collection_id"), table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index(op.f("ix_papers_semantic_scholar_id"), table_name="papers")
    op.drop_index(op.f("ix_papers_published_at"), table_name="papers")
    op.drop_index(op.f("ix_papers_pmid"), table_name="papers")
    op.drop_index(op.f("ix_papers_openalex_id"), table_name="papers")
    op.drop_index(op.f("ix_papers_doi"), table_name="papers")
    op.drop_index(op.f("ix_papers_deleted_at"), table_name="papers")
    op.drop_index(op.f("ix_papers_arxiv_id"), table_name="papers")
    op.drop_table("papers")
    op.drop_index(op.f("ix_authors_semantic_scholar_id"), table_name="authors")
    op.drop_index(op.f("ix_authors_orcid"), table_name="authors")
    op.drop_index(op.f("ix_authors_openalex_id"), table_name="authors")
    op.drop_index(op.f("ix_authors_deleted_at"), table_name="authors")
    op.drop_table("authors")
    op.drop_index(op.f("ix_webhooks_user_id"), table_name="webhooks")
    op.drop_index(op.f("ix_webhooks_deleted_at"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_venues_openalex_id"), table_name="venues")
    op.drop_index(op.f("ix_venues_issn"), table_name="venues")
    op.drop_index(op.f("ix_venues_deleted_at"), table_name="venues")
    op.drop_table("venues")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_topics_deleted_at"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_deleted_at"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_rss_feeds_deleted_at"), table_name="rss_feeds")
    op.drop_table("rss_feeds")
    op.drop_index(op.f("ix_institutions_ror_id"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_openalex_id"), table_name="institutions")
    op.drop_index(op.f("ix_institutions_deleted_at"), table_name="institutions")
    op.drop_table("institutions")
    op.drop_index(op.f("ix_digests_user_id"), table_name="digests")
    op.drop_index(op.f("ix_digests_deleted_at"), table_name="digests")
    op.drop_table("digests")
    op.drop_index(op.f("ix_collections_user_id"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_alert_rules_user_id"), table_name="alert_rules")
    op.drop_index(op.f("ix_alert_rules_deleted_at"), table_name="alert_rules")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
