"""initial_p0_schema

Revision ID: 625357ed3fc8
Revises: 
Create Date: 2026-03-20 16:15:00.340223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '625357ed3fc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('ror_id', sa.String(length=30), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_deleted_at'), 'institutions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_institutions_openalex_id'), 'institutions', ['openalex_id'], unique=True)
    op.create_index(op.f('ix_institutions_ror_id'), 'institutions', ['ror_id'], unique=False)
    op.create_table('rss_feeds',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('last_modified', sa.String(length=100), nullable=True),
    sa.Column('poll_error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('total_items_discovered', sa.Integer(), nullable=False),
    sa.Column('last_item_count', sa.Integer(), nullable=False),
    sa.Column('pdf_capability', sa.String(length=20), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_rss_feeds_deleted_at'), 'rss_feeds', ['deleted_at'], unique=False)
    op.create_table('venues',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('issn', sa.String(length=20), nullable=True),
    sa.Column('eissn', sa.String(length=20), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('homepage_url', sa.Text(), nullable=True),
    sa.Column('sjr_quartile', sa.String(length=5), nullable=True),
    sa.Column('ccf_rank', sa.String(length=5), nullable=True),
    sa.Column('impact_factor', sa.Float(), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_deleted_at'), 'venues', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_venues_issn'), 'venues', ['issn'], unique=False)
    op.create_index(op.f('ix_venues_openalex_id'), 'venues', ['openalex_id'], unique=True)
    op.create_table('authors',
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('orcid', sa.String(length=30), nullable=True),
    sa.Column('semantic_scholar_id', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('h_index', sa.Integer(), nullable=True),
    sa.Column('paper_count', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_deleted_at'), 'authors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_authors_openalex_id'), 'authors', ['openalex_id'], unique=True)
    op.create_index(op.f('ix_authors_orcid'), 'authors', ['orcid'], unique=False)
    op.create_index(op.f('ix_authors_semantic_scholar_id'), 'authors', ['semantic_scholar_id'], unique=False)
    op.create_table('papers',
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('openalex_id', sa.String(length=50), nullable=True),
    sa.Column('semantic_scholar_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('paper_type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('issue', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('oa_status', sa.String(length=20), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('influential_citation_count', sa.Integer(), nullable=True),
    sa.Column('citation_count_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('remote_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_full_text', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('grobid_tei', sa.Text(), nullable=True),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('parser_version', sa.String(length=20), nullable=True),
    sa.Column('ingestion_error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('highlights_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contributions_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('limitations_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_papers_deleted_at'), 'papers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_openalex_id'), 'papers', ['openalex_id'], unique=False)
    op.create_index(op.f('ix_papers_pmid'), 'papers', ['pmid'], unique=False)
    op.create_index(op.f('ix_papers_published_at'), 'papers', ['published_at'], unique=False)
    op.create_index(op.f('ix_papers_semantic_scholar_id'), 'papers', ['semantic_scholar_id'], unique=False)
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.Column('raw_affiliation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'author_id')
    )
    op.create_table('paper_references',
    sa.Column('citing_paper_id', sa.UUID(), nullable=False),
    sa.Column('cited_paper_id', sa.UUID(), nullable=True),
    sa.Column('raw_title', sa.Text(), nullable=True),
    sa.Column('raw_authors', sa.Text(), nullable=True),
    sa.Column('raw_year', sa.String(length=10), nullable=True),
    sa.Column('raw_doi', sa.String(length=255), nullable=True),
    sa.Column('raw_string', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_references_cited_paper_id'), 'paper_references', ['cited_paper_id'], unique=False)
    op.create_index(op.f('ix_paper_references_citing_paper_id'), 'paper_references', ['citing_paper_id'], unique=False)
    op.create_table('paper_versions',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('arxiv_version', sa.String(length=10), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_versions_deleted_at'), 'paper_versions', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_versions_deleted_at'), table_name='paper_versions')
    op.drop_table('paper_versions')
    op.drop_index(op.f('ix_paper_references_citing_paper_id'), table_name='paper_references')
    op.drop_index(op.f('ix_paper_references_cited_paper_id'), table_name='paper_references')
    op.drop_table('paper_references')
    op.drop_table('paper_authors')
    op.drop_index(op.f('ix_papers_semantic_scholar_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_published_at'), table_name='papers')
    op.drop_index(op.f('ix_papers_pmid'), table_name='papers')
    op.drop_index(op.f('ix_papers_openalex_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_deleted_at'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_authors_semantic_scholar_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_orcid'), table_name='authors')
    op.drop_index(op.f('ix_authors_openalex_id'), table_name='authors')
    op.drop_index(op.f('ix_authors_deleted_at'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_venues_openalex_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_issn'), table_name='venues')
    op.drop_index(op.f('ix_venues_deleted_at'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_rss_feeds_deleted_at'), table_name='rss_feeds')
    op.drop_table('rss_feeds')
    op.drop_index(op.f('ix_institutions_ror_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_openalex_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_deleted_at'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
